### ISSUE TITLE
Loosing true_user

### ISSUE THREAD

**Issue by jamsi** [ankane/pretender#5]
We seem to be experiencing an issue where (quite magically) the true_user is lost and our admin staff suddenly just "become" the user. Perhaps the session timing out?

Any ideas what could be causing this?

**Comment by ankane** [comment]
Which authentication framework do you use?

**Comment by jamsi** [comment]
Devise.

**Comment by sheffler** [comment]
Nice gem, but I have the same issue.  Browsing (viewing) impersonated users seems to work ok, but if I attempt to *edit* a user-setting, I suddenly become that user.  HEre is what I know.

I am using Devise with a custom registrations controller.

    # routes.rb
      devise_for :users, :controllers => { :registrations => "registrations" }

In that registrations_controller, I am attempting to let a *user* (real or impersonated) change various settings without entering a password.  (The exceptions are the password field itself.)  HEre is the excerpt from the registrations_controller.

    def update_resource(resource, params)
      if (not params[:password].blank?) or (not params[:password_confirmation].blank?)
        resource.update_with_password(params)
      else
        resource.update_without_password(params)
      end

If I impersonate a user and then change a non-password setting, I am suddenly that user.  Something to do with devise ...
  end

**Comment by paulewetzel** [comment]
I just noticed I had the same problem, also using devise. The true user is dropped when it I update a user.

**Comment by ShadowRadiance** [comment]
I realize this is a necro, but since it isn't closed, others may find their way here.

Devise logs you out when editing "your own" details. Since you're impersonating "User 12" when you edit the user setting, Devise seems to log out everything. 

You need to (re)sign_in (all) the user(s) after making the change. 

See 

sign_in @user, bypass: true

https://github.com/plataformatec/devise/issues/971
https://github.com/plataformatec/devise/issues/1039

**Comment by ankane** [comment]
Thanks for the explanation @ShadowRadiance
